In [1]:
import pandas as pd

In [9]:
df = pd.read_csv('../data/house_race_2020_clean.csv')
df

,Candidate,Party,Vote,State,District,Incumbent,Winner,Raised,Spent
0,Jerry Carl,R,64.9,Alabama,1,False,True,1971321,1859349
1,James Averhart,D,35.0,Alabama,1,False,False,80095,78973
2,Barry Moore,R,65.3,Alabama,2,False,True,650807,669368
3,Phyllis Harvey-Hall,D,34.6,Alabama,2,False,False,56050,55988
4,Mike D,R,67.5,Alabama,3,True,True,1193111,1218564
...,...,...,...,...,...,...,...,...,...
888,Tricia Zunker,D,39.2,Wisconsin,7,False,False,1261957,1232690
889,Mike Gallagher,R,64.0,Wisconsin,8,True,True,3202905,2841801
890,Amanda Stuck,D,36.0,Wisconsin,8,False,False,416978,399916
891,Liz Cheney,R,68.6,Wyoming,1,True,True,3003883,3060167
892,Lynnette Grey,D,24.6,Wyoming,1,False,False,134597,132235

In [6]:
georgia_rows = {'Candidate': ['Nikema Williams','Angela Stanton'],
               'Party':['D','R'],
               'Vote': [85.2, 14.9],
               'State': ['Georgia','Georgia'],
               'District':[5,5],
               'Incumbent':[False,False],
               'Winner': [True,False],
               'Raised': [553964,305279],
               'Spent': [362801,301338]}

In [20]:
df = pd.concat([df, pd.DataFrame(georgia_rows)]).reset_index(drop = True)
df

,Candidate,Party,Vote,State,District,Incumbent,Winner,Raised,Spent
0,Jerry Carl,R,64.9,Alabama,1,False,True,1971321,1859349
1,James Averhart,D,35.0,Alabama,1,False,False,80095,78973
2,Barry Moore,R,65.3,Alabama,2,False,True,650807,669368
3,Phyllis Harvey-Hall,D,34.6,Alabama,2,False,False,56050,55988
4,Mike D,R,67.5,Alabama,3,True,True,1193111,1218564
...,...,...,...,...,...,...,...,...,...
890,Amanda Stuck,D,36.0,Wisconsin,8,False,False,416978,399916
891,Liz Cheney,R,68.6,Wyoming,1,True,True,3003883,3060167
892,Lynnette Grey,D,24.6,Wyoming,1,False,False,134597,132235
893,Nikema Williams,D,85.2,Georgia,5,False,True,553964,362801
894,Angela Stanton,R,14.9,Georgia,5,False,False,305279,301338

In [22]:
df

,Candidate,Party,Vote,State,District,Incumbent,Winner,Raised,Spent
0,Jerry Carl,R,64.9,Alabama,1,False,True,1971321,1859349
1,James Averhart,D,35.0,Alabama,1,False,False,80095,78973
2,Barry Moore,R,65.3,Alabama,2,False,True,650807,669368
3,Phyllis Harvey-Hall,D,34.6,Alabama,2,False,False,56050,55988
4,Mike D,R,67.5,Alabama,3,True,True,1193111,1218564
...,...,...,...,...,...,...,...,...,...
890,Amanda Stuck,D,36.0,Wisconsin,8,False,False,416978,399916
891,Liz Cheney,R,68.6,Wyoming,1,True,True,3003883,3060167
892,Lynnette Grey,D,24.6,Wyoming,1,False,False,134597,132235
893,Nikema Williams,D,85.2,Georgia,5,False,True,553964,362801
894,Angela Stanton,R,14.9,Georgia,5,False,False,305279,301338

In [21]:
df.to_csv('../data/house_race_2020_clean.csv')